apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
